[[news]]
date = "May 2026"
content = "I passed my PhD preliminary exam and am now a Ph.D. candidate."

[[news]]
date = "Apr. 2026"
content = "Our preprint Braess' Paradoxes in Coupled Power and Transportation Systems was revised on arXiv."

[[news]]
date = "Dec. 2025"
content = "Our preprint Braess' Paradoxes in Coupled Power and Transportation Systems was posted on arXiv."

[[news]]
date = "Dec. 2023"
content = "Our paper Nexus Cognizant Pricing of Workplace Electric Vehicle Charging was accepted to the American Control Conference 2024."

[[news]]
date = "May 2023"
content = "I graduated from The Chinese University of Hong Kong, Shenzhen with first-class honors."
